config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "pages#home"
  get "/index", to: "pages#index"
  get "/dashboard", to: "pages#dashboard"

  resources :chat_rooms

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :all_except, ->(user) { where.not(id: user) }

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  # Pundit: allow-list approach

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_rooms.all
  end

  def create
  end

  def new
    @chat_rooms = ChatRoom.new
  end
end

app/controllers/mesagges_controller.rb
class MesaggesController < ApplicationController
  def index
  end

  def show
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
  def show
    @chat_rooms.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/new.html.erb
<div class="container">
  <%= simple_form_for(@chat_rooms) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-2 mb-2">
      <h1>Welcome to your Dashboard, <%= current_user.username %>!</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3>Profile</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <%= cl_image_tag current_user.photo.key, height: 300, width: 300, crop: :fill %>
    </div>
    <div class="profilinfo col-4">
      <p>username: <%= current_user.username %><p>
      <p>city: <%= current_user.city %></p>
      <p>about you: <%= current_user.aboutme %></p>
    </div>
    <div class="updateprofile col-4">
      <%= link_to "Update your profile", edit_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
<div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
  <h3>This is the new Chatt app</h3>

  <h4>Chat with your friends around the world</h4>
<%= link_to "Start now", new_user_session_path, class:"btn btn-primary" %>
  </div>

app/views/pages/index.html.erb
<h1>This is my Index page</h1>

<%= link_to "Let's create a chat room", new_chat_room_path, class:"btn btn-primary" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <i class="fa-solid fa-messages"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Chat Rooms", chat_rooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>